### ISSUE TITLE
Use argparse or validate args

### ISSUE THREAD

**Issue by bdhhtb** [joshuacw/fibonacci_visuals#1]
Either way it'd be good to get a friendly usage message instead of an IndexError when I type

```
python fib_numbers.py
```

**Comment by joshuacw** [comment]
I implemented argparse into the fib_numbers.py code. I'll probably make it a little bit more thorough, as I still feel I'm fumbling about when I'm implementing that module, and still don't fully understand it (but slowly getting a bit more comfortable with it). I do have one question though. In the code, you'll see `term = args.integer` towards the beginning. But when I just used  `args.integer` for function definitions (as opposed to `term`), I got syntax errors with the caret pointing to the dot. Do you know why this is???

**Comment by bdhhtb** [comment]
Nice job on argparse. As for your syntax error, please try this:
- Change the two occurrences of `term` in line 16 to `args.integer`. Run the program and confirm that all is well.
- Change `term` in line 23 to `args.integer`. Run and verify.
- Change `term` in line 24 to `args.integer`. Run and verify.
- If all that worked, try deleting line 10. Run and verify, then let's chat.

**Comment by joshuacw** [comment]
I deleted everything you suggested, and the code still runs properly (phew!). I understand why it works this way, but I still don't understand why I got those syntax errors with the previous code. :/
