### ISSUE TITLE
Move functions to a package

### ISSUE THREAD

**Issue by bdhhtb** [joshuacw/fibonacci_visuals#3]
Create a `util` or `fib_math` directory, then move `nth_term`, `fib_list`, `prime_list` functions there, and then import these functions in `bokeh_fib_numbers.py` and `fib_numbers.py`.

**Comment by joshuacw** [comment]
I had thought about doing something like this before you mentioned it. What benefit does this get me?

**Comment by bdhhtb** [comment]
A nice, clean, readable, fit-in-your-brain-able main function. It will make you feel so good.

**Comment by joshuacw** [comment]
I moved all of the functions to a package, and bokeh_fib_numbers.py still works. Should I rename it to "main.py"? Or does it even matter?

**Comment by bdhhtb** [comment]
Doesn't matter. `fib.py` or `fibonacci.py` or `main.py` or `fib_vis.py` or ... whatever. Can always rename it later. Have fun.
