### ISSUE TITLE
Make bokeh output optional

### ISSUE THREAD

**Issue by bdhhtb** [joshuacw/fibonacci_visuals#4]
Add a command line argument/flag to run the program without opening a browser or displaying visuals. Something you could run like this:

```
python bokeh_fib_numbers.py 23 --text-only
```

**Comment by joshuacw** [comment]
Actually, I wanted to see if I could incorporate the CL output into the browser page. The CL output related to the last function that I just wrote may disappear as the information will be incorporated in the graphical output.

**Comment by bdhhtb** [comment]
Definitely incorporate it into the page! But adding a `--text-only` mode is useful for debugging. (You can run semi-broken code over and over without fooling with opening a browser tab.) You could just call it `--debug` mode I guess.

**Comment by joshuacw** [comment]
Haha! How funny you bring this up. This is exactly what I'm going through right now. I found out that my code doesn't work with small integers.

**Comment by joshuacw** [comment]
Do you know if argparse would be able to take care of this?

**Comment by bdhhtb** [comment]
For sure! Something like

`parser.add_argument('--debug', '-d', action='store_true')`

and then later

```
if args.debug:
  do stuff
```
