### ISSUE TITLE
Add to README

### ISSUE THREAD

**Issue by bdhhtb** [joshuacw/fibonacci_visuals#5]
What kinds of visualizations, data, and interactivity do you plan to add?

**Comment by joshuacw** [comment]
-A visual showing how well approximation of phi matches true value
-The squares/spiral is possible
-I've thought about adding a slide bar (or something similar) for the number of terms.

Will do more reading re: the fib. seq. for other neat things to possibly show

**Comment by bdhhtb** [comment]
Cool, I recommend going ahead and adding this to the README as an exercise to clarify what you're after and also to make the project look more exciting :)
